//! Client-side synced resources and WebSocket lifecycle.
//!
//! Helpers for Leptos components that subscribe to Photon topics over WebSocket and
//! keep [`Resource`] data fresh when events arrive.
//!
//! ## Choosing a sync strategy
//!
//! | Strategy | When to use |
//! |---------|-------------|
//! | [`SyncStrategy::Refetch`](crate::SyncStrategy::Refetch) | Server owns query logic (lists, joins, auth-scoped reads) |
//! | [`SyncStrategy::Replace`](crate::SyncStrategy::Replace) | WS payload is the full new value (scalars, simple structs) |
//! | [`SyncStrategy::Append`](crate::SyncStrategy::Append) | Feed-style lists — use [`synced_resource_append`] |
//!
//! ## API tiers
//!
//! | Tier | API | Use when |
//! |------|-----|----------|
//! | 2 (macro) | `use_<fn>()` from `#[photon_leptos::synced]` | Single resource, convention-based |
//! | 1 | [`use_topic_subscription`] | Multiple resources/effects on one WS path |
//! | 0 | [`subscribe_ws`] | Custom callback handling of raw payloads |
//!
//! ### Helper example (without macro)
//!
//! ```rust,ignore
//! use photon_leptos::{synced_resource, SyncStrategy, SyncedResourceOpts};
//!
//! pub fn use_notifications() -> Resource<Result<Vec<Notification>, ServerFnError>> {
//!     synced_resource(
//!         list_notifications,
//!         SyncedResourceOpts {
//!             topic: "notifications.updated".into(),
//!             ws_path: "/ws/notifications".into(),
//!             strategy: SyncStrategy::Refetch,
//!             key_filter: None,
//!         },
//!     )
//! }
//! ```
//!
//! On SSR-only builds, WebSocket calls compile out; triggers stay at 0 and initial
//! values come from server-rendered [`Resource`] fetches.
//!
//! ## WebSocket client contract
//!
//! [`subscribe_ws`] documents the leptos-use feature-unification hazard and the
//! `message.get()` + `Effect` pattern required for connections to open. Do not
//! refactor that helper without running browser E2E (see repository `e2e/README.md`).
//!
//! Uses `leptos_use::use_websocket` for connection management (reconnect,
//! cleanup, protocol resolution).

use crate::SyncedResourceOpts;
use codee::string::FromToStringCodec;
use leptos::prelude::*;
use leptos_use::{use_websocket_with_options, UseWebSocketOptions, UseWebSocketReturn};
use std::future::Future;

/// Photon Event shape (minimal for payload extraction).
#[derive(serde::Deserialize)]
struct PhotonEvent {
    #[serde(rename = "payload_json")]
    payload_json: serde_json::Value,
}

// ---------------------------------------------------------------------------
// Public API — Tier 1: shared subscription primitive
// ---------------------------------------------------------------------------

/// Reactive handle to a Photon WebSocket topic subscription.
///
/// Multiple resources and effects can depend on the same `trigger` signal
/// so they all react to the same WS event without opening separate
/// connections.
///
/// # Example — two resources on one topic
///
/// ```rust,ignore
/// let sub = use_topic_subscription("/ws/notifications");
///
/// let count = Resource::new(move || sub.trigger.get(), move |_| get_unread_count());
/// let list  = Resource::new(move || sub.trigger.get(), move |_| get_list());
///
/// // Force refresh from outside (e.g. after marking a notification read):
/// sub.refetch();
/// ```
#[derive(Clone, Copy)]
pub struct PhotonSubscription {
    /// Bumped on every incoming WS event. Depend on this to refetch.
    pub trigger: RwSignal<u64>,
    /// The latest event payload (useful for Replace-strategy consumers).
    pub latest_event: RwSignal<Option<serde_json::Value>>,
}

impl PhotonSubscription {
    /// Force a trigger bump from outside the WS callback — e.g. after a
    /// local mutation that should refresh all dependent resources.
    pub fn refetch(&self) {
        self.trigger.update(|n| *n += 1);
    }
}

/// Create a shared subscription to a Photon WebSocket endpoint.
///
/// Returns a [`PhotonSubscription`] whose `trigger` signal bumps on every
/// incoming event. Wire any number of `Resource`s, `Effect`s, or
/// `use_paged_infinite_scroll` hooks to this trigger.
///
/// This is the **Tier 1** primitive. For the common one-resource case, use
/// the `use_<fn_name>()` hook generated by `#[photon_leptos::synced]` instead.
pub fn use_topic_subscription(ws_path: &str) -> PhotonSubscription {
    let trigger = RwSignal::new(0u64);
    let latest_event: RwSignal<Option<serde_json::Value>> = RwSignal::new(None);

    subscribe_ws(ws_path, move |payload| {
        latest_event.set(Some(payload));
        trigger.update(|n| *n += 1);
    });

    PhotonSubscription {
        trigger,
        latest_event,
    }
}

// ---------------------------------------------------------------------------
// Public API — Tier 0: raw callback subscription
// ---------------------------------------------------------------------------

/// Subscribe to a Photon WebSocket and call `on_event` for each incoming
/// message payload.  The connection is automatically managed by
/// `leptos_use::use_websocket` (reconnect, cleanup on owner disposal).
///
/// This is the lowest-level primitive — it does not create signals or
/// resources.  Prefer [`use_topic_subscription`] for most use cases.
///
/// # Implementation contract (do not change without E2E verification)
///
/// ## Cargo feature-unification hazard
///
/// `leptos-use` uses `#[cfg(feature = "ssr")]` internally: when `ssr` is
/// active, `use_websocket_with_options` compiles the `open`/`close`/`send`
/// closures as **no-ops** and the WebSocket never connects. Cargo unifies
/// features **per package across the entire target**, so if **any** crate
/// in the dependency graph enables `leptos-use/ssr` unconditionally (even
/// a crate unrelated to WebSockets), every crate's leptos-use gets `ssr`
/// and the WebSocket silently dies on the client. The symptom is:
/// `subscribing to WebSocket` logs in the browser, but no `on_open`,
/// `on_message`, or connection activity at all.
///
/// **Rule:** every crate that depends on `leptos-use` must gate `ssr`
/// behind its own `ssr` feature — never put it in unconditional
/// `[dependencies]` features.
///
/// ## `message.get()` + `Effect` pattern
///
/// The connection lifecycle depends on **destructuring `UseWebSocketReturn`
/// and reading `message.get()` inside an `Effect`**:
///
/// 1. `let UseWebSocketReturn { message, .. }` — the `message` signal is a
///    reactive handle into leptos-use's internal connection state.
/// 2. `Effect::new(move |_| { message.get(); … })` — the `Effect` registers
///    with the current reactive owner and the `.get()` call subscribes to the
///    signal, which keeps leptos-use's internal connection `Effect` tracked
///    and scheduled.
/// 3. Dropping the `UseWebSocketReturn` (e.g. `let _ = use_websocket_with_options(…)`)
///    or replacing `message.get()` with `.on_message()` callbacks alone will
///    cause the WebSocket to never connect.
///
/// **Do not** refactor to `.on_message()` callbacks without the `message.get()`
/// `Effect`, and **do not** bind the return value to `_`.
pub fn subscribe_ws(ws_path: &str, on_event: impl Fn(serde_json::Value) + Send + Sync + 'static) {
    log::info!("[photon-leptos] subscribing to WebSocket {}", ws_path);

    let UseWebSocketReturn { message, .. } =
        use_websocket_with_options::<String, String, FromToStringCodec, _, _>(
            ws_path,
            UseWebSocketOptions::default()
                .reconnect_limit(leptos_use::ReconnectLimit::Limited(u64::MAX))
                .reconnect_interval(3_000)
                .on_error({
                    let ws_path = ws_path.to_string();
                    move |err| {
                        log::warn!("[photon-leptos] WebSocket error on {}: {:?}", ws_path, err);
                    }
                }),
        );

    Effect::new(move |_prev| {
        if let Some(text) = message.get() {
            match serde_json::from_str::<PhotonEvent>(&text) {
                Ok(photon_ev) => {
                    log::info!("[photon-leptos] received event on WS, dispatching");
                    on_event(photon_ev.payload_json);
                }
                Err(e) => {
                    let preview: String = text.chars().take(256).collect();
                    log::warn!(
                        "[photon-leptos] WebSocket message is not a Photon event envelope ({}): {:?}",
                        e,
                        preview
                    );
                }
            }
        }
    });
}

/// Creates a Leptos resource that stays in sync with Photon events via WebSocket.
///
/// When an event is received on the WebSocket, the resource is refetched (or the
/// configured strategy is applied). The WebSocket connection is closed when the
/// reactive owner is disposed (component unmount).
///
/// # Arguments
///
/// * `fetcher` - Closure that returns the async fetch (e.g. a server function call)
/// * `opts` - Configuration for topic, WebSocket path, and sync strategy
pub fn synced_resource<F, Fut, T>(fetcher: F, opts: SyncedResourceOpts) -> Resource<T>
where
    F: Fn() -> Fut + Send + Sync + 'static,
    Fut: Future<Output = T> + Send + 'static,
    T: serde::Serialize + serde::de::DeserializeOwned + Send + Sync + Clone + PartialEq + 'static,
{
    match opts.strategy {
        crate::SyncStrategy::Refetch => synced_resource_refetch(fetcher, opts),
        crate::SyncStrategy::Replace => synced_resource_replace(fetcher, opts),
        crate::SyncStrategy::Append => {
            log::warn!(
                "photon-leptos: Append strategy requires synced_resource_append; using Refetch"
            );
            synced_resource_refetch(fetcher, opts)
        }
    }
}

/// Creates a synced resource for appendable lists. When an event arrives, the
/// payload is deserialized as `U` and appended to the current list.
/// Returns `Resource<Option<Result<Vec<U>, E>>>` — `None` while loading.
pub fn synced_resource_append<F, Fut, U, E>(
    fetcher: F,
    opts: SyncedResourceOpts,
) -> Resource<Option<Result<Vec<U>, E>>>
where
    F: Fn() -> Fut + Send + Sync + 'static,
    Fut: Future<Output = Result<Vec<U>, E>> + Send + 'static,
    U: serde::Serialize + serde::de::DeserializeOwned + Send + Sync + Clone + PartialEq + 'static,
    E: Send + Sync + Clone + PartialEq + serde::Serialize + serde::de::DeserializeOwned + 'static,
{
    use leptos::task::spawn_local;

    let data_signal: RwSignal<Option<Result<Vec<U>, E>>> = RwSignal::new(None);
    let data_clone = data_signal;

    spawn_local(async move {
        let val = fetcher().await;
        data_clone.set(Some(val));
    });

    let data_clone_for_res = data_signal;
    let resource = Resource::new(
        move || data_signal.get(),
        move |_| std::future::ready(data_clone_for_res.get()),
    );

    let data_for_ws = data_signal;
    subscribe_ws(&opts.ws_path, move |payload_json| {
        if let Ok(item) = serde_json::from_value::<U>(payload_json) {
            data_for_ws.update(|opt| {
                if let Some(Ok(vec)) = opt {
                    vec.push(item);
                }
            });
        }
    });

    resource
}

// ---------------------------------------------------------------------------
// Internal
// ---------------------------------------------------------------------------

/// Replace strategy: initial value from the server function (SSR safe),
/// then subsequent updates written directly from the WS payload — no
/// server round-trip.  Falls back to refetch if the payload can't be
/// deserialized into `T`.
fn synced_resource_replace<F, Fut, T>(fetcher: F, opts: SyncedResourceOpts) -> Resource<T>
where
    F: Fn() -> Fut + Send + Sync + 'static,
    Fut: Future<Output = T> + Send + 'static,
    T: serde::Serialize + serde::de::DeserializeOwned + Send + Sync + Clone + PartialEq + 'static,
{
    let trigger = RwSignal::new(0u64);
    let direct_value: RwSignal<Option<T>> = RwSignal::new(None);

    let resource = Resource::new(
        move || (trigger.get(), direct_value.get()),
        move |(_, injected)| {
            let fetcher_fut = fetcher();
            async move {
                if let Some(val) = injected {
                    val
                } else {
                    fetcher_fut.await
                }
            }
        },
    );

    log::info!(
        "[photon-leptos] synced_resource: topic={}, ws_path={}, strategy=Replace",
        opts.topic,
        opts.ws_path
    );

    let ws_path_for_log = opts.ws_path.clone();
    subscribe_ws(
        &opts.ws_path,
        move |payload_json| match serde_json::from_value::<T>(payload_json) {
            Ok(value) => {
                log::info!(
                    "[photon-leptos] received event on {}, applying Replace",
                    ws_path_for_log
                );
                direct_value.set(Some(value));
                trigger.update(|n| *n += 1);
            }
            Err(e) => {
                log::warn!(
                    "[photon-leptos] Replace: payload deserialization failed ({}), falling back to refetch",
                    e
                );
                direct_value.set(None);
                trigger.update(|n| *n += 1);
            }
        },
    );

    resource
}

fn synced_resource_refetch<F, Fut, T>(fetcher: F, opts: SyncedResourceOpts) -> Resource<T>
where
    F: Fn() -> Fut + Send + Sync + 'static,
    Fut: Future<Output = T> + Send + 'static,
    T: serde::Serialize + serde::de::DeserializeOwned + Send + Sync + 'static,
{
    let trigger = RwSignal::new(0u64);

    let resource = Resource::new(move || trigger.get(), move |_| fetcher());

    log::info!(
        "[photon-leptos] synced_resource: topic={}, ws_path={}, strategy=Refetch",
        opts.topic,
        opts.ws_path
    );

    let ws_path_for_log = opts.ws_path.clone();
    subscribe_ws(&opts.ws_path, move |_| {
        log::info!(
            "[photon-leptos] received event on {}, triggering refetch",
            ws_path_for_log
        );
        trigger.update(|n| *n += 1);
    });

    resource
}
