//! Synced counter server functions (client + server).

#![allow(non_snake_case)] // generated by #[photon_leptos::synced]

use leptos::prelude::*;
use photon_leptos::synced;

#[cfg(feature = "ssr")]
use crate::state::AppState;

#[cfg(feature = "ssr")]
async fn namespace_from_request() -> Result<String, ServerFnError> {
    if let Some(ns) = use_context::<String>() {
        return Ok(ns);
    }
    use axum::http::HeaderMap;
    let headers: HeaderMap = leptos_axum::extract()
        .await
        .map_err(|e| ServerFnError::new(e.to_string()))?;
    if let Some(cookie) = headers.get(axum::http::header::COOKIE) {
        for part in cookie.to_str().unwrap_or_default().split(';') {
            if let Some(ns) = part.trim().strip_prefix("e2e_ns=") {
                return Ok(ns.to_string());
            }
        }
    }
    Err(ServerFnError::new("missing namespace context"))
}

#[server]
#[synced(
    topic = "counter.updated",
    ws = "/ws/counter",
    auth = "none"
)]
pub async fn counter_get() -> Result<u64, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let namespace = namespace_from_request().await?;
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        let flags = state.store.flags(&namespace);
        if flags.fail_read {
            return Err(ServerFnError::ServerError("counter read failed".into()));
        }
        Ok(state.store.get(&namespace))
    }
    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::ServerError(
            "counter_get requires SSR".into(),
        ))
    }
}

#[server]
#[synced(
    topic = "counter.auth.updated",
    ws = "/ws/counter-auth",
    auth = "user"
)]
pub async fn counter_get_auth_user() -> Result<u64, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let namespace = namespace_from_request().await?;
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        Ok(state.store.get(&namespace))
    }
    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::ServerError(
            "counter_get_auth_user requires SSR".into(),
        ))
    }
}
