//! Synced counter server functions (client + server).

#![allow(non_snake_case)] // generated by #[photon_leptos::synced]

use leptos::prelude::*;
use photon_leptos::synced;

#[cfg(feature = "ssr")]
use crate::state::AppState;

#[cfg(feature = "ssr")]
async fn namespace_from_request() -> Result<String, ServerFnError> {
    if let Some(ns) = use_context::<String>() {
        return Ok(ns);
    }
    use axum::http::HeaderMap;
    let headers: HeaderMap = leptos_axum::extract()
        .await
        .map_err(|e| ServerFnError::new(e.to_string()))?;
    if let Some(cookie) = headers.get(axum::http::header::COOKIE) {
        for part in cookie.to_str().unwrap_or_default().split(';') {
            if let Some(ns) = part.trim().strip_prefix("e2e_ns=") {
                return Ok(ns.to_string());
            }
        }
    }
    Err(ServerFnError::new("missing namespace context"))
}

#[cfg(feature = "ssr")]
async fn partition_from_request() -> Result<String, ServerFnError> {
    use super::context::E2ePartition;

    if let Some(E2ePartition(p)) = use_context::<E2ePartition>() {
        return Ok(p);
    }
    use crate::auth::{cookie_value, E2E_USER_COOKIE};
    use axum::http::HeaderMap;

    let headers: HeaderMap = leptos_axum::extract()
        .await
        .map_err(|e| ServerFnError::new(e.to_string()))?;
    if let Some(user) = cookie_value(&headers, E2E_USER_COOKIE) {
        return Ok(user);
    }
    cookie_value(&headers, "e2e_key")
        .ok_or_else(|| ServerFnError::new("missing partition identity"))
}

#[server]
#[synced(topic = "counter.updated", ws = "/ws/counter", auth = "none")]
pub async fn counter_get() -> Result<u64, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let namespace = namespace_from_request().await?;
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        let flags = state.store.flags(&namespace);
        if flags.fail_read {
            return Err(ServerFnError::ServerError("counter read failed".into()));
        }
        Ok(state.store.get(&namespace))
    }
    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::ServerError(
            "counter_get requires SSR".into(),
        ))
    }
}

/// Auth-scoped keyed read (`auth = "user"`, key from session cookie).
#[server]
#[synced(
    topic = "counter.keyed.updated",
    ws = "/ws/counter-auth",
    auth = "user"
)]
pub async fn counter_get_auth_user() -> Result<u64, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let namespace = namespace_from_request().await?;
        let user = partition_from_request().await?;
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        Ok(state.store.get_partition(&namespace, &user))
    }
    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::ServerError(
            "counter_get_auth_user requires SSR".into(),
        ))
    }
}

/// Key-only / auth+key read path — same topic; client passes `?key=` on WS.
///
/// Server fn reads the partition from the `e2e_key` cookie (set by the page) so
/// refetch returns the correct partition counter.
#[server]
#[synced(
    topic = "counter.keyed.updated",
    ws = "/ws/counter-keyed",
    auth = "none"
)]
pub async fn counter_get_keyed() -> Result<u64, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let namespace = namespace_from_request().await?;
        let key = partition_from_request().await?;
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        Ok(state.store.get_partition(&namespace, &key))
    }
    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::ServerError(
            "counter_get_keyed requires SSR".into(),
        ))
    }
}

/// Auth + client key combination route (`auth = "user"` + client `?key=`).
#[server]
#[synced(
    topic = "counter.keyed.updated",
    ws = "/ws/counter-auth-key",
    auth = "user"
)]
pub async fn counter_get_auth_key() -> Result<u64, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let namespace = namespace_from_request().await?;
        let user = partition_from_request().await?;
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        Ok(state.store.get_partition(&namespace, &user))
    }
    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::ServerError(
            "counter_get_auth_key requires SSR".into(),
        ))
    }
}
