//! Synced reads, topics, and teaching mutations.

#![allow(non_snake_case)] // generated by #[photon_leptos::synced]

use leptos::prelude::*;
use photon_leptos::synced;

#[cfg(feature = "ssr")]
use crate::state::AppState;

/// Partition / user id provided by the page (SSR + cookie mirror).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DemoPartition(pub String);

#[cfg(feature = "ssr")]
mod topics {
    use photon::topic;

    #[topic(name = "demo.counter.updated")]
    pub struct CounterUpdated;

    #[topic(name = "demo.counter.keyed.updated", keyed_by = "partition")]
    pub struct CounterKeyedUpdated {
        pub partition: String,
    }
}

#[cfg(feature = "ssr")]
async fn partition_from_request() -> Result<String, ServerFnError> {
    if let Some(DemoPartition(p)) = use_context::<DemoPartition>() {
        return Ok(p);
    }
    use crate::auth::{cookie_value, DEMO_USER_COOKIE};
    use axum::http::HeaderMap;

    let headers: HeaderMap = leptos_axum::extract()
        .await
        .map_err(|e| ServerFnError::new(e.to_string()))?;
    if let Some(user) = cookie_value(&headers, DEMO_USER_COOKIE) {
        return Ok(user);
    }
    cookie_value(&headers, "demo_key").ok_or_else(|| ServerFnError::new("missing partition"))
}

/// Broadcast counter — `strategy = "refetch"` (default).
#[server]
#[synced(topic = "demo.counter.updated", ws = "/ws/counter", auth = "none")]
pub async fn counter_get() -> Result<u64, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        Ok(state.store.get())
    }
    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::ServerError("ssr required".into()))
    }
}

/// Auth-scoped keyed read.
#[server]
#[synced(
    topic = "demo.counter.keyed.updated",
    ws = "/ws/counter-auth",
    auth = "user"
)]
pub async fn counter_get_auth() -> Result<u64, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let partition = partition_from_request().await?;
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        Ok(state.store.get_partition(&partition))
    }
    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::ServerError("ssr required".into()))
    }
}

/// Key-only partition read (`auth = "none"` + client `?key=`).
#[server]
#[synced(
    topic = "demo.counter.keyed.updated",
    ws = "/ws/counter-keyed",
    auth = "none"
)]
pub async fn counter_get_keyed() -> Result<u64, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let partition = partition_from_request().await?;
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        Ok(state.store.get_partition(&partition))
    }
    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::ServerError("ssr required".into()))
    }
}

/// Mutate broadcast counter and publish (any open `/` tab refetches).
#[server]
pub async fn increment_broadcast() -> Result<(), ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        use topics::CounterUpdated;
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        state.store.increment();
        CounterUpdated {}
            .publish()
            .await
            .map_err(|e| ServerFnError::new(e.to_string()))?;
        Ok(())
    }
    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::ServerError("ssr required".into()))
    }
}

/// Mutate a partition and publish a keyed event.
#[server]
pub async fn increment_partition(partition: String) -> Result<(), ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        use topics::CounterKeyedUpdated;
        let state =
            use_context::<AppState>().ok_or_else(|| ServerFnError::new("missing AppState"))?;
        state.store.increment_partition(&partition);
        CounterKeyedUpdated { partition }
            .publish()
            .await
            .map_err(|e| ServerFnError::new(e.to_string()))?;
        Ok(())
    }
    #[cfg(not(feature = "ssr"))]
    {
        let _ = partition;
        Err(ServerFnError::ServerError("ssr required".into()))
    }
}
